[package]
name = "node-android"
version = "0.1.0"
edition = "2021"

[lib]
name = "nodenative"
crate-type = ["cdylib"]

[dependencies]
node-c = { path = "../../libs/node-c" }
#node-core = {path = "../../libs/node-core"}
#node-buffer = { path = "../../libs/node-buffer" }
#node-fs = { path = "../../libs/node-fs" }
#jni = "0.21.1"
#once_cell = "1.17.2"
#libc = "0.2.144"
#parking_lot = "0.12.1"
#android_logger = "0.13.1"
